import { SEO } from "@/components/SEO";
import { Container, PageHero, CTA, CardGrid } from "@/components/Blocks";

export default function ProofLibraryPage() {
  return (
    <>
      <SEO
        title="Proof Library — Kincaid IQ"
        description="Searchable repository of evidence receipts, audit trails, and decision artifacts. CFO-grade documentation for every value event."
      />
      <Container>
        <PageHero
          title="Proof Library"
          subtitle="Searchable repository of evidence receipts, audit trails, and decision artifacts. CFO-grade documentation for every value event."
        />

        <div className="space-y-16">
          <section>
            <h2 className="text-2xl font-semibold mb-6">What Is the Proof Library?</h2>
            <div className="k-panel p-8">
              <p className="text-white/70 leading-relaxed">
                The Proof Library is a centralized, searchable repository of all <strong className="text-white">evidence receipts</strong>,
                audit trails, and decision artifacts generated by Kincaid IQ. It ensures that every value claim, every
                savings calculation, and every operational decision is backed by traceable, timestamped, cryptographically
                verified evidence.
              </p>
              <p className="text-white/70 leading-relaxed mt-4">
                CFOs, auditors, and compliance teams can query the library to answer questions like:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-6 mt-4 text-white/70">
                <li>What evidence supports this $500K rebate claim?</li>
                <li>When was this data last refreshed?</li>
                <li>Who approved this decision and when?</li>
                <li>What was the confidence score of this anomaly detection?</li>
                <li>Can I trace this value back to the source query in Snowflake?</li>
              </ul>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-6">Receipt Structure</h2>
            <div className="k-panel p-8">
              <div className="font-mono text-sm bg-white/5 p-6 rounded-lg border border-white/10 overflow-x-auto">
                {`{
  "id": "rcpt-pbm-q4-2025-variance",
  "title": "PBM rebate variance analysis Q4 2025",
  "hash": "sha256:a1b2c3d4e5f6...",
  "freshness": "PT10M",
  "confidence": 0.94,
  "sourceSystem": "snowflake",
  "sourceRef": "query-abc-123-456",
  "url": "https://app.snowflake.com/...",
  "createdAt": "2025-12-15T14:30:00Z",
  "meta": {
    "warehouse": "ANALYTICS_WH",
    "database": "CLAIMS",
    "schema": "PBM",
    "tables": ["REBATE_GUARANTEES", "ACTUAL_PAYMENTS"],
    "rowCount": 12847,
    "executionTime": "4.2s"
  }
}`}
              </div>
              <div className="mt-6 space-y-3 text-sm text-white/70">
                <p><strong className="text-white">id:</strong> Unique identifier for this receipt</p>
                <p><strong className="text-white">title:</strong> Human-readable description</p>
                <p><strong className="text-white">hash:</strong> SHA-256 hash of query results (tamper-proof)</p>
                <p><strong className="text-white">freshness:</strong> Age of data (ISO 8601 duration: PT10M = 10 minutes)</p>
                <p><strong className="text-white">confidence:</strong> ML model confidence score (0.0 - 1.0)</p>
                <p><strong className="text-white">sourceSystem:</strong> Origin system (snowflake, databricks, servicenow, etc.)</p>
                <p><strong className="text-white">sourceRef:</strong> Query ID or record ID in source system</p>
                <p><strong className="text-white">url:</strong> Direct link to evidence in source system</p>
                <p><strong className="text-white">meta:</strong> Additional context (warehouse, tables, execution stats)</p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-6">Key Features</h2>
            <CardGrid
              items={[
                {
                  title: "Cryptographic Hashing",
                  body: "SHA-256 hashes ensure data integrity. Any tampering or drift is immediately detectable.",
                },
                {
                  title: "Freshness Tracking",
                  body: "ISO 8601 durations (PT5M, PT1H, P1D) show data age. Alerts trigger when receipts become stale.",
                },
                {
                  title: "Confidence Scores",
                  body: "ML model confidence (0.0 - 1.0) indicates prediction reliability. Low confidence = manual review required.",
                },
                {
                  title: "Source Lineage",
                  body: "Direct links to Snowflake queries, Databricks notebooks, ServiceNow tickets. Full traceability.",
                },
                {
                  title: "Search & Filter",
                  body: "Query by date range, source system, confidence threshold, freshness, hash, or custom tags.",
                },
                {
                  title: "Audit Export",
                  body: "Export receipts to CSV/JSON for external audits, regulatory compliance, or board reporting.",
                },
              ]}
            />
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-6">Use Cases</h2>
            <div className="space-y-4">
              {[
                {
                  title: "CFO Audit Preparation",
                  desc: "Export all receipts for Q4 2025 with confidence > 0.9 and freshness < 24 hours. Provide to external auditors for verification.",
                },
                {
                  title: "Regulatory Compliance",
                  desc: "Prove that all rebate claims are backed by cryptographically verified evidence from Snowflake within 15 minutes of detection.",
                },
                {
                  title: "Dispute Resolution",
                  desc: "Vendor disputes $200K rebate claim. Provide receipt with hash, freshness, and direct Snowflake query link as proof.",
                },
                {
                  title: "Board Reporting",
                  desc: "Generate executive summary of all REALIZED value events with receipts showing source data lineage and confidence scores.",
                },
                {
                  title: "Data Quality Monitoring",
                  desc: "Alert when receipts show confidence < 0.7 or freshness > 1 hour. Trigger DQ investigation workflow.",
                },
                {
                  title: "Deterministic Replay",
                  desc: "Replay historical queries using stored query IDs. Validate that results match original receipt hashes (no data drift).",
                },
              ].map((useCase) => (
                <div key={useCase.title} className="k-panel p-6">
                  <div className="font-semibold text-white mb-2">{useCase.title}</div>
                  <div className="text-sm text-white/70">{useCase.desc}</div>
                </div>
              ))}
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-6">Integration with War Room & Ledger</h2>
            <div className="k-panel p-8">
              <p className="text-white/70 leading-relaxed">
                Every arbitrage event in the <strong className="text-white">War Room</strong> includes one or more receipts
                from the Proof Library. When an event is approved and moved to the{" "}
                <strong className="text-white">Verified Savings Ledger</strong>, the receipts travel with it, creating an
                immutable audit trail from discovery → approval → realization.
              </p>
              <div className="mt-6 space-y-3 text-sm">
                <div className="flex items-start gap-3">
                  <div className="text-emerald-400 font-mono">1.</div>
                  <div className="text-white/70">
                    <strong className="text-white">Discovery:</strong> Snowflake query detects $340K rebate variance
                  </div>
                </div>
                <div className="flex items-start gap-3">
                  <div className="text-emerald-400 font-mono">2.</div>
                  <div className="text-white/70">
                    <strong className="text-white">Receipt Generated:</strong> Hash, freshness, confidence recorded in Proof Library
                  </div>
                </div>
                <div className="flex items-start gap-3">
                  <div className="text-emerald-400 font-mono">3.</div>
                  <div className="text-white/70">
                    <strong className="text-white">War Room:</strong> Event surfaces with receipt badge ("🔒 Verified")
                  </div>
                </div>
                <div className="flex items-start gap-3">
                  <div className="text-emerald-400 font-mono">4.</div>
                  <div className="text-white/70">
                    <strong className="text-white">Approval:</strong> CFO reviews receipt, signs packet, moves to ledger
                  </div>
                </div>
                <div className="flex items-start gap-3">
                  <div className="text-emerald-400 font-mono">5.</div>
                  <div className="text-white/70">
                    <strong className="text-white">Ledger Entry:</strong> $340K moved to APPROVED state with receipt link
                  </div>
                </div>
                <div className="flex items-start gap-3">
                  <div className="text-emerald-400 font-mono">6.</div>
                  <div className="text-white/70">
                    <strong className="text-white">Realization:</strong> Rebate collected, ledger updated, receipt preserved
                  </div>
                </div>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-6">Security & Compliance</h2>
            <div className="k-panel p-8">
              <div className="space-y-4 text-white/70 leading-relaxed">
                <p>
                  The Proof Library is designed for <strong className="text-white">SOC 2 Type II</strong> and{" "}
                  <strong className="text-white">HIPAA</strong> compliance, with:
                </p>
                <ul className="list-disc list-inside space-y-2 ml-6">
                  <li><strong className="text-white">Immutable Storage:</strong> Receipts stored in append-only log (no deletion/modification)</li>
                  <li><strong className="text-white">Encryption at Rest:</strong> AES-256 encryption for all stored receipts</li>
                  <li><strong className="text-white">Access Logs:</strong> Every receipt access logged with user, timestamp, IP address</li>
                  <li><strong className="text-white">Role-Based Access:</strong> Granular permissions (viewer, operator, approver, admin)</li>
                  <li><strong className="text-white">Audit Exports:</strong> Tamper-proof exports with cryptographic signatures</li>
                  <li><strong className="text-white">Data Retention:</strong> Configurable retention (7 years default for financial records)</li>
                </ul>
              </div>
            </div>
          </section>

          <CTA />
        </div>
      </Container>
    </>
  );
}