import type { ContractAnalysisResult, RiskAssessment, ProvisionAnalysis } from "./types";

/**
 * Generate PDF-ready HTML report for contract analysis
 * This can be used with browser print or server-side PDF generation
 */
export function generateContractReport(
  contractName: string,
  analysis: ContractAnalysisResult
): string {
  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Contract Analysis Report - ${contractName}</title>
  <style>
    @page { margin: 0.75in; }
    body { font-family: 'Arial', sans-serif; color: #1a1a1a; line-height: 1.6; }
    .header { text-align: center; border-bottom: 3px solid #2563eb; padding-bottom: 20px; margin-bottom: 30px; }
    .header h1 { color: #2563eb; margin: 0; font-size: 28px; }
    .header .subtitle { color: #666; font-size: 14px; margin-top: 5px; }
    .section { margin-bottom: 30px; page-break-inside: avoid; }
    .section-title { color: #2563eb; font-size: 20px; border-bottom: 2px solid #e5e7eb; padding-bottom: 8px; margin-bottom: 15px; }
    .metric-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 15px; margin-bottom: 25px; }
    .metric-card { border: 1px solid #e5e7eb; border-radius: 8px; padding: 15px; text-align: center; }
    .metric-value { font-size: 32px; font-weight: bold; color: #2563eb; }
    .metric-label { font-size: 12px; color: #666; text-transform: uppercase; margin-top: 5px; }
    .risk-critical { color: #dc2626; }
    .risk-high { color: #ea580c; }
    .risk-medium { color: #eab308; }
    .risk-low { color: #16a34a; }
    .provision-table { width: 100%; border-collapse: collapse; margin-top: 15px; }
    .provision-table th { background: #f3f4f6; padding: 12px; text-align: left; font-size: 13px; border-bottom: 2px solid #e5e7eb; }
    .provision-table td { padding: 12px; border-bottom: 1px solid #e5e7eb; font-size: 13px; }
    .provision-table tr:hover { background: #f9fafb; }
    .score-badge { display: inline-block; padding: 4px 12px; border-radius: 12px; font-size: 11px; font-weight: 600; }
    .score-excellent { background: #dcfce7; color: #166534; }
    .score-good { background: #dbeafe; color: #1e40af; }
    .score-fair { background: #fef3c7; color: #92400e; }
    .score-poor { background: #fee2e2; color: #991b1b; }
    .red-flag { background: #fef2f2; border-left: 4px solid #dc2626; padding: 15px; margin: 10px 0; border-radius: 4px; }
    .red-flag-title { color: #dc2626; font-weight: 600; margin-bottom: 5px; }
    .savings { background: #f0fdf4; border-left: 4px solid #16a34a; padding: 15px; margin: 10px 0; border-radius: 4px; }
    .savings-amount { font-size: 28px; font-weight: bold; color: #16a34a; }
    .footer { margin-top: 50px; padding-top: 20px; border-top: 2px solid #e5e7eb; text-align: center; color: #666; font-size: 12px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>PBM Contract Analysis Report</h1>
    <div class="subtitle">Generated by SiriusB iQ Contract Intelligence Platform</div>
    <div class="subtitle">${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
  </div>

  <div class="section">
    <h2 class="section-title">Contract Overview</h2>
    <p><strong>Contract Name:</strong> ${contractName}</p>
    <p><strong>Analysis Date:</strong> ${new Date().toLocaleDateString()}</p>
    <p><strong>Status:</strong> Complete</p>
  </div>

  <div class="section">
    <h2 class="section-title">Executive Summary</h2>
    <div class="metric-grid">
      <div class="metric-card">
        <div class="metric-value risk-${analysis.riskLevel.toLowerCase()}">${analysis.overallScore}</div>
        <div class="metric-label">Overall Score</div>
      </div>
      <div class="metric-card">
        <div class="metric-value risk-${analysis.riskLevel.toLowerCase()}">${analysis.criticalIssuesCount}</div>
        <div class="metric-label">Critical Issues</div>
      </div>
      <div class="metric-card">
        <div class="metric-value">${analysis.totalRedFlags}</div>
        <div class="metric-label">Total Red Flags</div>
      </div>
      <div class="metric-card">
        <div class="metric-value risk-low">$${(analysis.estimatedSavings / 1000000).toFixed(1)}M</div>
        <div class="metric-label">Potential Savings</div>
      </div>
    </div>

    <div class="savings">
      <strong>Estimated Annual Savings Opportunity:</strong>
      <div class="savings-amount">$${analysis.estimatedSavings.toLocaleString()}</div>
      <p style="margin-top: 10px; color: #166534;">Based on industry benchmarks and identified contract inefficiencies</p>
    </div>
  </div>

  <div class="section">
    <h2 class="section-title">Provision Analysis</h2>
    <table class="provision-table">
      <thead>
        <tr>
          <th>Provision</th>
          <th>Score</th>
          <th>Risk Level</th>
          <th>Impact</th>
        </tr>
      </thead>
      <tbody>
        ${analysis.provisions.map(p => `
          <tr>
            <td><strong>${p.name}</strong></td>
            <td><span class="score-badge score-${getScoreBadge(p.score)}">${p.score}/100</span></td>
            <td class="risk-${p.riskLevel.toLowerCase()}">${p.riskLevel}</td>
            <td>$${p.estimatedImpact.toLocaleString()}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  </div>

  <div class="section">
    <h2 class="section-title">Critical Issues Identified</h2>
    ${analysis.redFlags.map(flag => `
      <div class="red-flag">
        <div class="red-flag-title">⚠️ ${flag.title}</div>
        <p>${flag.description}</p>
        <p><strong>Recommendation:</strong> ${flag.recommendation}</p>
      </div>
    `).join('')}
  </div>

  <div class="section">
    <h2 class="section-title">Risk Assessment</h2>
    <p><strong>Overall Risk Level:</strong> <span class="risk-${analysis.riskLevel.toLowerCase()}">${analysis.riskLevel}</span></p>
    <p><strong>Risk Score:</strong> ${analysis.overallScore}/100</p>
    <p>${getRiskDescription(analysis.riskLevel)}</p>
  </div>

  <div class="footer">
    <p>SiriusB iQ Contract Intelligence Platform</p>
    <p>This report is confidential and intended solely for the use of the recipient organization.</p>
    <p>© ${new Date().getFullYear()} SiriusB iQ. All rights reserved.</p>
  </div>
</body>
</html>
  `;

  return html;
}

function getScoreBadge(score: number): string {
  if (score >= 85) return 'excellent';
  if (score >= 70) return 'good';
  if (score >= 50) return 'fair';
  return 'poor';
}

function getRiskDescription(riskLevel: string): string {
  const descriptions = {
    Critical: 'This contract contains multiple provisions that pose significant financial and operational risks. Immediate renegotiation is strongly recommended.',
    High: 'Several concerning provisions were identified that could result in substantial cost overruns or operational constraints. Review and renegotiation is advised.',
    Medium: 'Some provisions may benefit from clarification or improvement, but the overall contract structure is acceptable.',
    Low: 'This contract contains favorable terms with minimal risk. Minor optimizations may still be possible.'
  };
  return descriptions[riskLevel as keyof typeof descriptions] || '';
}

/**
 * Trigger browser print dialog for PDF export
 */
export function exportToPDF(contractName: string, analysis: ContractAnalysisResult) {
  const reportHTML = generateContractReport(contractName, analysis);
  const printWindow = window.open('', '_blank');
  
  if (printWindow) {
    printWindow.document.write(reportHTML);
    printWindow.document.close();
    
    // Wait for content to load, then trigger print
    printWindow.onload = () => {
      printWindow.focus();
      printWindow.print();
    };
  }
}