import type { LaneKey, WarEvent, LaneSummary } from "@/lib/warroom/types";

export const laneMeta: Record<LaneKey, { label: string; headline: string }> = {
  value: { label: "Verified Savings Ledger", headline: "Reconcile value with receipts and owners." },
  controls: { label: "Controls & Compliance", headline: "Continuous controls. Evidence-first posture." },
  agentic: { label: "Agentic Ops & Sales", headline: "Governed automation with telemetry and gates." },
  marketplace: { label: "Marketplace Execution", headline: "Ship once. Distribute with low delivery drag." },
};

export function seedSummaries(): LaneSummary[] {
  return (Object.keys(laneMeta) as LaneKey[]).map((lane) => {
    const baseIdentified = lane === "value" ? 7_800_000 : lane === "controls" ? 2_100_000 : lane === "agentic" ? 3_400_000 : 1_250_000;
    return {
      lane,
      label: laneMeta[lane].label,
      headline: laneMeta[lane].headline,
      identified: baseIdentified,
      approved: baseIdentified * 0.37,
      realized: baseIdentified * 0.21,
      atRisk: baseIdentified * 0.13,
      velocity: lane === "value" ? 285000 : lane === "controls" ? 95000 : lane === "agentic" ? 142000 : 68000,
      avgConfidence: lane === "value" ? 0.84 : lane === "controls" ? 0.79 : lane === "agentic" ? 0.76 : 0.81,
      criticalCount: lane === "value" ? 7 : lane === "controls" ? 12 : lane === "agentic" ? 5 : 3,
      trendData: generateTrendData(12),
    };
  });
}

function generateTrendData(points: number): number[] {
  const data: number[] = [];
  let current = Math.random() * 50 + 50;
  for (let i = 0; i < points; i++) {
    data.push(current);
    current = current + (Math.random() - 0.4) * 15;
    current = Math.max(20, Math.min(100, current));
  }
  return data;
}

export function seedEvents(): WarEvent[] {
  const now = new Date().toISOString();
  
  const valueEvents: WarEvent[] = [
    {
      id: "evt-001",
      lane: "value",
      title: "PBM guarantee variance detected (audit-grade receipts ready)",
      subtitle: "Potential reconciliation against contract guarantees",
      amount: 420_000,
      confidence: 0.86,
      timeSensitivity: 0.74,
      state: "IDENTIFIED",
      owner: "Finance Ops",
      category: "PBM Reconciliation",
      priority: "HIGH",
      trend: 12.5,
      daysInState: 3,
      receipts: [
        { id: "r-1", title: "Contract guarantee schedule", hash: "0xA13...", freshness: "2h ago" },
        { id: "r-2", title: "Claims reconciliation report", hash: "0xB24...", freshness: "4h ago" }
      ],
      updatedAt: now,
    },
    {
      id: "evt-005",
      lane: "value",
      title: "Cloud cost optimization: reserved instance arbitrage captured",
      subtitle: "AWS RI commitment vs on-demand spread",
      amount: 340_000,
      confidence: 0.91,
      timeSensitivity: 0.58,
      state: "APPROVED",
      owner: "FinOps",
      category: "Cloud Optimization",
      priority: "MEDIUM",
      trend: 8.3,
      daysInState: 12,
      receipts: [
        { id: "r-7", title: "AWS Cost Explorer export", hash: "0xG45...", freshness: "1h ago" }
      ],
      updatedAt: now,
    },
    {
      id: "evt-101",
      lane: "value",
      title: "Stop-loss reimbursement recovery identified",
      subtitle: "High-cost claimant threshold breach tracking",
      amount: 580_000,
      confidence: 0.88,
      timeSensitivity: 0.82,
      state: "APPROVED",
      owner: "Benefits Finance",
      category: "Stop-Loss",
      priority: "CRITICAL",
      trend: 15.2,
      daysInState: 6,
      receipts: [
        { id: "r-11", title: "Stop-loss carrier file", hash: "0xK91...", freshness: "3h ago" }
      ],
      updatedAt: now,
    },
    {
      id: "evt-102",
      lane: "value",
      title: "Duplicate claims pattern detected via ML model",
      subtitle: "Systematic duplicate billing across 3 providers",
      amount: 215_000,
      confidence: 0.79,
      timeSensitivity: 0.91,
      state: "IDENTIFIED",
      owner: "Claims Analytics",
      category: "Fraud Detection",
      priority: "HIGH",
      trend: -5.1,
      daysInState: 1,
      receipts: [
        { id: "r-12", title: "ML anomaly report", hash: "0xL47...", freshness: "6h ago" }
      ],
      updatedAt: now,
    },
    {
      id: "evt-103",
      lane: "value",
      title: "Network discount variance: actual vs contracted rates",
      subtitle: "Provider billing above contracted fee schedule",
      amount: 390_000,
      confidence: 0.83,
      timeSensitivity: 0.67,
      state: "REALIZED",
      owner: "Network Ops",
      category: "Network Pricing",
      priority: "MEDIUM",
      trend: 6.7,
      daysInState: 45,
      receipts: [
        { id: "r-13", title: "Fee schedule audit", hash: "0xM83...", freshness: "5h ago" }
      ],
      updatedAt: now,
    },
    {
      id: "evt-104",
      lane: "value",
      title: "Pharmacy rebate true-up Q4 variance",
      subtitle: "Rebate guarantee shortfall identified",
      amount: 725_000,
      confidence: 0.94,
      timeSensitivity: 0.88,
      state: "APPROVED",
      owner: "Pharmacy Finance",
      category: "PBM Reconciliation",
      priority: "CRITICAL",
      trend: 22.8,
      daysInState: 8,
      receipts: [
        { id: "r-14", title: "PBM rebate statement", hash: "0xN29...", freshness: "2h ago" }
      ],
      updatedAt: now,
    },
    {
      id: "evt-105",
      lane: "value",
      title: "Dependent eligibility audit findings",
      subtitle: "Ineligible dependents still on plan coverage",
      amount: 168_000,
      confidence: 0.76,
      timeSensitivity: 0.72,
      state: "AT_RISK",
      owner: "Benefits Ops",
      category: "Eligibility",
      priority: "HIGH",
      trend: -8.4,
      daysInState: 22,
      receipts: [
        { id: "r-15", title: "Eligibility audit results", hash: "0xO55...", freshness: "8h ago" }
      ],
      updatedAt: now,
    },
    {
      id: "evt-106",
      lane: "value",
      title: "SaaS license optimization: unused seats identified",
      subtitle: "Salesforce + ServiceNow license waste",
      amount: 142_000,
      confidence: 0.89,
      timeSensitivity: 0.45,
      state: "REALIZED",
      owner: "IT Finance",
      category: "SaaS Optimization",
      priority: "LOW",
      trend: 4.2,
      daysInState: 67,
      receipts: [
        { id: "r-16", title: "License usage report", hash: "0xP71...", freshness: "12h ago" }
      ],
      updatedAt: now,
    },
  ];

  const controlEvents: WarEvent[] = [
    {
      id: "evt-002",
      lane: "controls",
      title: "Eligibility-feed control drift: stale file freshness threshold breached",
      subtitle: "Control gate failed; requires owner acknowledgement",
      amount: -120_000,
      confidence: 0.78,
      timeSensitivity: 0.82,
      state: "AT_RISK",
      owner: "Data Governance",
      category: "Data Quality",
      priority: "CRITICAL",
      trend: -12.3,
      daysInState: 2,
      receipts: [
        { id: "r-3", title: "Freshness check report", hash: "0xC77...", freshness: "1h ago" }
      ],
      updatedAt: now,
    },
    {
      id: "evt-006",
      lane: "controls",
      title: "SOC 2 Type II prep: 3 control gaps closed with automation",
      subtitle: "Evidence collection now continuous",
      amount: 180_000,
      confidence: 0.82,
      timeSensitivity: 0.66,
      state: "REALIZED",
      owner: "InfoSec",
      category: "Compliance",
      priority: "HIGH",
      trend: 18.5,
      daysInState: 34,
      receipts: [
        { id: "r-8", title: "Control testing results", hash: "0xH23...", freshness: "5h ago" }
      ],
      updatedAt: now,
    },
    {
      id: "evt-201",
      lane: "controls",
      title: "Claims audit trail gaps detected in 847 transactions",
      subtitle: "Missing audit signatures in legacy system",
      amount: -85_000,
      confidence: 0.81,
      timeSensitivity: 0.89,
      state: "IDENTIFIED",
      owner: "Audit Team",
      category: "Audit Compliance",
      priority: "HIGH",
      trend: -6.7,
      daysInState: 5,
      receipts: [
        { id: "r-21", title: "Audit trail report", hash: "0xQ88...", freshness: "4h ago" }
      ],
      updatedAt: now,
    },
    {
      id: "evt-202",
      lane: "controls",
      title: "Access control review: 23 orphaned admin accounts",
      subtitle: "Terminated employees still have system access",
      amount: -145_000,
      confidence: 0.92,
      timeSensitivity: 0.95,
      state: "AT_RISK",
      owner: "IAM Team",
      category: "Access Control",
      priority: "CRITICAL",
      trend: -15.8,
      daysInState: 1,
      receipts: [
        { id: "r-22", title: "Access review findings", hash: "0xR33...", freshness: "2h ago" }
      ],
      updatedAt: now,
    },
    {
      id: "evt-203",
      lane: "controls",
      title: "HIPAA compliance: encryption at rest implemented",
      subtitle: "All PII/PHI now encrypted with KMS",
      amount: 210_000,
      confidence: 0.87,
      timeSensitivity: 0.71,
      state: "APPROVED",
      owner: "Security Eng",
      category: "Compliance",
      priority: "HIGH",
      trend: 11.4,
      daysInState: 18,
      receipts: [
        { id: "r-23", title: "Encryption audit", hash: "0xS66...", freshness: "6h ago" }
      ],
      updatedAt: now,
    },
    {
      id: "evt-204",
      lane: "controls",
      title: "Data lineage tracking: 98% coverage achieved",
      subtitle: "Critical fields now fully traceable",
      amount: 95_000,
      confidence: 0.79,
      timeSensitivity: 0.54,
      state: "REALIZED",
      owner: "Data Eng",
      category: "Data Governance",
      priority: "MEDIUM",
      trend: 7.9,
      daysInState: 56,
      receipts: [
        { id: "r-24", title: "Lineage coverage report", hash: "0xT91...", freshness: "9h ago" }
      ],
      updatedAt: now,
    },
  ];

  const agenticEvents: WarEvent[] = [
    {
      id: "evt-003",
      lane: "agentic",
      title: "Agent workflow: quote-to-cash cycle time reduced 12%",
      subtitle: "Telemetry confirms sustained improvement",
      amount: 210_000,
      confidence: 0.73,
      timeSensitivity: 0.40,
      state: "REALIZED",
      owner: "RevOps",
      category: "Sales Automation",
      priority: "MEDIUM",
      trend: 9.2,
      daysInState: 28,
      receipts: [
        { id: "r-4", title: "Agent telemetry snapshot", hash: "0xD09...", freshness: "30m ago" },
        { id: "r-5", title: "Cycle time baseline", hash: "0xE12...", freshness: "6h ago" }
      ],
      updatedAt: now,
    },
    {
      id: "evt-007",
      lane: "agentic",
      title: "Sales agent hallucination rate: 2.4% → 0.7% after guardrail update",
      subtitle: "Confidence layer prevents bad quotes",
      amount: 125_000,
      confidence: 0.76,
      timeSensitivity: 0.71,
      state: "IDENTIFIED",
      owner: "Sales Ops",
      category: "Agent Quality",
      priority: "HIGH",
      trend: 14.6,
      daysInState: 4,
      receipts: [
        { id: "r-9", title: "Hallucination audit log", hash: "0xI56...", freshness: "2h ago" }
      ],
      updatedAt: now,
    },
    {
      id: "evt-301",
      lane: "agentic",
      title: "Customer support agent: CSAT score up 18 points",
      subtitle: "AI-powered resolution quality improvement",
      amount: 285_000,
      confidence: 0.81,
      timeSensitivity: 0.63,
      state: "APPROVED",
      owner: "Support Ops",
      category: "Support Automation",
      priority: "HIGH",
      trend: 16.3,
      daysInState: 14,
      receipts: [
        { id: "r-31", title: "CSAT tracking data", hash: "0xU44...", freshness: "5h ago" }
      ],
      updatedAt: now,
    },
    {
      id: "evt-302",
      lane: "agentic",
      title: "Contract analysis agent: 4.2 days → 6 hours review time",
      subtitle: "Legal team bandwidth freed up 73%",
      amount: 340_000,
      confidence: 0.88,
      timeSensitivity: 0.55,
      state: "REALIZED",
      owner: "Legal Ops",
      category: "Legal Automation",
      priority: "MEDIUM",
      trend: 12.1,
      daysInState: 42,
      receipts: [
        { id: "r-32", title: "Contract processing metrics", hash: "0xV77...", freshness: "7h ago" }
      ],
      updatedAt: now,
    },
    {
      id: "evt-303",
      lane: "agentic",
      title: "Lead qualification agent: conversion rate +23%",
      subtitle: "Better lead scoring drives pipeline quality",
      amount: 475_000,
      confidence: 0.79,
      timeSensitivity: 0.68,
      state: "APPROVED",
      owner: "Marketing Ops",
      category: "Sales Automation",
      priority: "CRITICAL",
      trend: 19.7,
      daysInState: 9,
      receipts: [
        { id: "r-33", title: "Lead scoring analysis", hash: "0xW22...", freshness: "4h ago" }
      ],
      updatedAt: now,
    },
    {
      id: "evt-304",
      lane: "agentic",
      title: "Expense approval agent: policy compliance 94% → 99%",
      subtitle: "Automated policy enforcement reduces leakage",
      amount: 156_000,
      confidence: 0.84,
      timeSensitivity: 0.59,
      state: "IDENTIFIED",
      owner: "Finance Ops",
      category: "Finance Automation",
      priority: "MEDIUM",
      trend: 8.8,
      daysInState: 7,
      receipts: [
        { id: "r-34", title: "Expense policy audit", hash: "0xX55...", freshness: "8h ago" }
      ],
      updatedAt: now,
    },
  ];

  const marketplaceEvents: WarEvent[] = [
    {
      id: "evt-004",
      lane: "marketplace",
      title: "Marketplace onboarding: time-to-value down to 9 days",
      subtitle: "Standardized pack reduced services drag",
      amount: 95_000,
      confidence: 0.69,
      timeSensitivity: 0.35,
      state: "APPROVED",
      owner: "Delivery",
      category: "Onboarding",
      priority: "MEDIUM",
      trend: 6.4,
      daysInState: 11,
      receipts: [
        { id: "r-6", title: "Onboarding checklist + receipts", hash: "0xF11...", freshness: "3h ago" }
      ],
      updatedAt: now,
    },
    {
      id: "evt-008",
      lane: "marketplace",
      title: "Snowflake marketplace: 4 new customers via native listing",
      subtitle: "Zero sales motion, pure discovery",
      amount: 280_000,
      confidence: 0.88,
      timeSensitivity: 0.44,
      state: "REALIZED",
      owner: "Partnerships",
      category: "Marketplace Sales",
      priority: "HIGH",
      trend: 24.5,
      daysInState: 21,
      receipts: [
        { id: "r-10", title: "Snowflake transaction log", hash: "0xJ78...", freshness: "4h ago" }
      ],
      updatedAt: now,
    },
    {
      id: "evt-401",
      lane: "marketplace",
      title: "AWS Marketplace integration: 2 enterprise deals closed",
      subtitle: "Private offers via marketplace accelerate procurement",
      amount: 420_000,
      confidence: 0.91,
      timeSensitivity: 0.72,
      state: "APPROVED",
      owner: "Cloud Partnerships",
      category: "Marketplace Sales",
      priority: "CRITICAL",
      trend: 31.2,
      daysInState: 5,
      receipts: [
        { id: "r-41", title: "AWS marketplace report", hash: "0xY88...", freshness: "3h ago" }
      ],
      updatedAt: now,
    },
    {
      id: "evt-402",
      lane: "marketplace",
      title: "Partner enablement: certification time reduced 40%",
      subtitle: "Self-service training portal driving faster ramp",
      amount: 125_000,
      confidence: 0.77,
      timeSensitivity: 0.51,
      state: "REALIZED",
      owner: "Partner Success",
      category: "Partner Enablement",
      priority: "MEDIUM",
      trend: 11.8,
      daysInState: 38,
      receipts: [
        { id: "r-42", title: "Training completion metrics", hash: "0xZ33...", freshness: "6h ago" }
      ],
      updatedAt: now,
    },
    {
      id: "evt-403",
      lane: "marketplace",
      title: "API marketplace: 12 integrations published",
      subtitle: "Developer ecosystem expansion driving usage",
      amount: 195_000,
      confidence: 0.73,
      timeSensitivity: 0.48,
      state: "IDENTIFIED",
      owner: "Platform",
      category: "API Ecosystem",
      priority: "LOW",
      trend: 8.1,
      daysInState: 16,
      receipts: [
        { id: "r-43", title: "API usage analytics", hash: "0xA99...", freshness: "9h ago" }
      ],
      updatedAt: now,
    },
  ];

  const arbitrageEvents: WarEvent[] = [
    {
      id: "ARB-10901",
      lane: "value",
      title: "Anthem Admin Fee Variance vs Schedule C",
      subtitle: "Detected mismatch between carrier-stated admin fees and 5500-derived compensation trail.",
      amount: 780_000,
      confidence: 0.95,
      timeSensitivity: 0.9,
      state: "IDENTIFIED",
      owner: "CFO Office",
      category: "Fee Reconciliation",
      priority: "CRITICAL",
      type: "arbitrage",
      carrier: "Anthem BCBS",
      estImpact: "$420k–$780k",
      priority_score: 95,
      trend: 15.2,
      daysInState: 1,
      receipts: [],
      updatedAt: now,
    },
    {
      id: "ARB-10902",
      lane: "value",
      title: "UnitedHealth Network Steering Spread",
      subtitle: "Plan design constraints appear to force utilization into higher-cost tiers.",
      amount: 540_000,
      confidence: 0.88,
      timeSensitivity: 0.85,
      state: "APPROVED",
      owner: "Benefits Team",
      category: "Network Pricing",
      priority: "HIGH",
      type: "arbitrage",
      carrier: "UnitedHealthcare",
      estImpact: "$310k–$540k",
      priority_score: 88,
      trend: 12.4,
      daysInState: 4,
      receipts: [],
      updatedAt: now,
    },
    {
      id: "ARB-10903",
      lane: "value",
      title: "Cigna Rx Rebate Under-Remittance Risk",
      subtitle: "Rebate terms may exclude specialty and certain channels.",
      amount: 610_000,
      confidence: 0.82,
      timeSensitivity: 0.8,
      state: "IDENTIFIED",
      owner: "Pharmacy Analytics",
      category: "Pharmacy Benefits",
      priority: "HIGH",
      type: "arbitrage",
      carrier: "Cigna",
      estImpact: "$260k–$610k",
      priority_score: 82,
      trend: 8.9,
      daysInState: 2,
      receipts: [],
      updatedAt: now,
    },
    {
      id: "ARB-10904",
      lane: "controls",
      title: "Aetna Stop-Loss Attachment Shift",
      subtitle: "Attachment point change creates EBITDA-at-risk variance under current claims trend.",
      amount: 360_000,
      confidence: 0.65,
      timeSensitivity: 0.7,
      state: "AT_RISK",
      owner: "Risk Analytics",
      category: "Risk Management",
      priority: "MEDIUM",
      type: "arbitrage",
      carrier: "Aetna",
      estImpact: "$180k–$360k",
      priority_score: 65,
      trend: -5.4,
      daysInState: 7,
      receipts: [],
      updatedAt: now,
    },
    {
      id: "ARB-10905",
      lane: "value",
      title: "Duplicate PEPM Vendor Charges",
      subtitle: "Two overlapping vendors billing PEPM for similar services.",
      amount: 210_000,
      confidence: 0.58,
      timeSensitivity: 0.6,
      state: "APPROVED",
      owner: "Procurement",
      category: "Vendor Management",
      priority: "MEDIUM",
      type: "arbitrage",
      carrier: "Multiple Vendors",
      estImpact: "$95k–$210k",
      priority_score: 58,
      trend: 6.1,
      daysInState: 14,
      receipts: [],
      updatedAt: now,
    },
    {
      id: "ARB-10906",
      lane: "value",
      title: "Express Scripts MAC Spread Pricing Signal",
      subtitle: "Observed spread indicators across generics vs benchmark.",
      amount: 1100000,
      confidence: 0.92,
      timeSensitivity: 0.95,
      state: "IDENTIFIED",
      owner: "Pharmacy Analytics",
      category: "PBM Audit",
      priority: "CRITICAL",
      type: "arbitrage",
      carrier: "Express Scripts",
      estImpact: "$520k–$1.1M",
      priority_score: 92,
      trend: 22.1,
      daysInState: 1,
      receipts: [],
      updatedAt: now,
    },
    {
      id: "ARB-10907",
      lane: "controls",
      title: "Humana Utilization Management Fee Opacity",
      subtitle: "UM fees not fully disclosed in contract. Cross-reference with actual claims adjudication.",
      amount: 480_000,
      confidence: 0.75,
      timeSensitivity: 0.75,
      state: "IDENTIFIED",
      owner: "Finance Team",
      category: "Fee Reconciliation",
      priority: "HIGH",
      type: "arbitrage",
      carrier: "Humana",
      estImpact: "$225k–$480k",
      priority_score: 75,
      trend: 9.8,
      daysInState: 3,
      receipts: [],
      updatedAt: now,
    },
    {
      id: "ARB-10908",
      lane: "value",
      title: "Kaiser Capitation Rate Reconciliation Gap",
      subtitle: "Capitation payments exceed contracted rates by 3.2%.",
      amount: 290_000,
      confidence: 0.60,
      timeSensitivity: 0.5,
      state: "REALIZED",
      owner: "Finance Team",
      category: "Payment Reconciliation",
      priority: "MEDIUM",
      type: "arbitrage",
      carrier: "Kaiser Permanente",
      estImpact: "$145k–$290k",
      priority_score: 60,
      trend: 4.5,
      daysInState: 45,
      receipts: [],
      updatedAt: now,
    },
  ];

  return [...valueEvents, ...controlEvents, ...agenticEvents, ...marketplaceEvents, ...arbitrageEvents];
}

export function formatMoney(n: number) {
  const abs = Math.abs(n);
  const sign = n < 0 ? "-" : "";
  if (abs >= 1_000_000_000) return `${sign}$${(abs / 1_000_000_000).toFixed(2)}B`;
  if (abs >= 1_000_000) return `${sign}$${(abs / 1_000_000).toFixed(2)}M`;
  if (abs >= 1_000) return `${sign}$${(abs / 1_000).toFixed(1)}K`;
  return `${sign}$${abs.toFixed(0)}`;
}

export function mockWarRoom() {
  return {
    actual: 12.4,
    baseline: 8.2,
    delta: 4.2,
    ebitda: {
      ytd_validated: 4500000,
      mtd_validated: 850000,
      confidence: 0.92
    },
    ledger: {
      identified: 12500000,
      approved: 8400000,
      realized: 4500000,
      at_risk: 1200000
    },
    data_health: {
      verified_receipts_rate: 0.88,
      dq_pass_rate: 0.96,
      freshness_hours: 1.2
    },
    events: [
      {
        id: "EVT-2024-001",
        title: "PBM Contract Guarantee Variance",
        type: "PBM",
        status: "RECOMMENDED",
        identified_value: 450000,
        confidence: 0.85,
        time_sensitivity: 0.92,
        execution_friction: 0.65,
        score: 92,
        owner_role: "Director of Pharmacy",
        evidence_receipt_id: "RCP-9832",
        receipt_status: "VERIFIED",
        theme: "rose"
      },
      {
        id: "EVT-2024-002",
        title: "High-Cost Claimant Stop-Loss Trigger",
        type: "MEDICAL",
        status: "ACCEPTED",
        identified_value: 280000,
        confidence: 0.94,
        time_sensitivity: 0.88,
        execution_friction: 0.35,
        score: 88,
        owner_role: "Benefits Manager",
        evidence_receipt_id: "RCP-7721",
        receipt_status: "DEGRADED",
        theme: "blue"
      },
      {
        id: "EVT-2024-003",
        title: "Duplicate Specialty Drug Claim",
        type: "PBM",
        status: "VALIDATED",
        identified_value: 125000,
        confidence: 0.99,
        time_sensitivity: 0.45,
        execution_friction: 0.20,
        score: 85,
        owner_role: "Claims Auditor",
        evidence_receipt_id: "RCP-GL-001",
        receipt_status: "VERIFIED",
        theme: "emerald"
      },
      {
        id: "EVT-2024-004",
        title: "Network Discount Leakage",
        type: "MEDICAL",
        status: "IMPLEMENTED",
        identified_value: 340000,
        confidence: 0.82,
        time_sensitivity: 0.75,
        execution_friction: 0.55,
        score: 79,
        owner_role: "Network Ops",
        evidence_receipt_id: "RCP-IMP-001",
        receipt_status: "VERIFIED",
        theme: "cyan"
      },
      {
        id: "EVT-2024-005",
        title: "Rebate True-up Mismatch",
        type: "PBM",
        status: "UNVERIFIED",
        identified_value: 180000,
        confidence: 0.78,
        time_sensitivity: 0.60,
        execution_friction: 0.45,
        score: 74,
        owner_role: "Finance Lead",
        evidence_receipt_id: "RCP-4556",
        receipt_status: "UNVERIFIED",
        theme: "amber"
      },
      {
        id: "ARB-10901",
        title: "Anthem Admin Fee Variance vs Schedule C",
        type: "ARBITRAGE",
        status: "RECOMMENDED",
        identified_value: 780000,
        confidence: 0.95,
        time_sensitivity: 0.90,
        execution_friction: 0.45,
        score: 95,
        owner_role: "CFO Office",
        evidence_receipt_id: "RCP-ARB-001",
        receipt_status: "VERIFIED",
        theme: "rose",
        carrier: "Anthem BCBS",
        estImpact: "$420k–$780k",
        subtitle: "Detected mismatch between carrier-stated admin fees and 5500-derived compensation trail"
      },
      {
        id: "ARB-10902",
        title: "UnitedHealth Network Steering Spread",
        type: "ARBITRAGE",
        status: "ACCEPTED",
        identified_value: 540000,
        confidence: 0.88,
        time_sensitivity: 0.85,
        execution_friction: 0.55,
        score: 88,
        owner_role: "Benefits Team",
        evidence_receipt_id: "RCP-ARB-002",
        receipt_status: "VERIFIED",
        theme: "violet",
        carrier: "UnitedHealthcare",
        estImpact: "$310k–$540k",
        subtitle: "Plan design constraints force utilization into higher-cost tiers"
      },
      {
        id: "ARB-10903",
        title: "Cigna Rx Rebate Under-Remittance Risk",
        type: "ARBITRAGE",
        status: "RECOMMENDED",
        identified_value: 610000,
        confidence: 0.82,
        time_sensitivity: 0.80,
        execution_friction: 0.60,
        score: 82,
        owner_role: "Pharmacy Analytics",
        evidence_receipt_id: "RCP-ARB-003",
        receipt_status: "DEGRADED",
        theme: "amber",
        carrier: "Cigna",
        estImpact: "$260k–$610k",
        subtitle: "Rebate terms may exclude specialty and certain channels"
      },
      {
        id: "ARB-10904",
        title: "Express Scripts MAC Spread Pricing Signal",
        type: "ARBITRAGE",
        status: "IMPLEMENTED",
        identified_value: 1100000,
        confidence: 0.92,
        time_sensitivity: 0.95,
        execution_friction: 0.50,
        score: 92,
        owner_role: "Pharmacy Analytics",
        evidence_receipt_id: "RCP-ARB-004",
        receipt_status: "VERIFIED",
        theme: "rose",
        carrier: "Express Scripts",
        estImpact: "$520k–$1.1M",
        subtitle: "Observed spread indicators across generics vs benchmark"
      },
      {
        id: "ARB-10905",
        title: "Humana Utilization Management Fee Opacity",
        type: "ARBITRAGE",
        status: "ACCEPTED",
        identified_value: 480000,
        confidence: 0.75,
        time_sensitivity: 0.75,
        execution_friction: 0.65,
        score: 75,
        owner_role: "Finance Team",
        evidence_receipt_id: "RCP-ARB-005",
        receipt_status: "VERIFIED",
        theme: "cyan",
        carrier: "Humana",
        estImpact: "$225k–$480k",
        subtitle: "UM fees not fully disclosed in contract"
      },
      {
        id: "ARB-10906",
        title: "Kaiser Capitation Rate Reconciliation Gap",
        type: "ARBITRAGE",
        status: "VALIDATED",
        identified_value: 290000,
        confidence: 0.60,
        time_sensitivity: 0.50,
        execution_friction: 0.40,
        score: 60,
        owner_role: "Finance Team",
        evidence_receipt_id: "RCP-ARB-006",
        receipt_status: "VERIFIED",
        theme: "emerald",
        carrier: "Kaiser Permanente",
        estImpact: "$145k–$290k",
        subtitle: "Capitation payments exceed contracted rates by 3.2%"
      }
    ],
    drivers: [
      { label: "PBM Guarantees", delta_pct: 1.8 },
      { label: "Stop-Loss Recoveries", delta_pct: 1.2 },
      { label: "Network Discounts", delta_pct: 0.8 },
      { label: "Clinical Edits", delta_pct: 0.4 }
    ],
    asOf: new Date().toISOString()
  };
}