// This file is automatically generated. Do not edit it directly.
// Types are generated from the Supabase database schema using the Supabase CLI.

import type { Database as DatabaseGenerated } from "./database.types";

export type Database = DatabaseGenerated;

export type SupabaseClient = import("@supabase/supabase-js").SupabaseClient<Database>;

// Re-export commonly used types for convenience
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T];
export type Functions<T extends keyof Database['public']['Functions']> = Database['public']['Functions'][T];

// Project reference: uhhuxprbxioarcbalzlg
// Last updated: 2026-05-20T06:56:04.099667
