import type { NextApiRequest, NextApiResponse } from "next";
import type { SnapshotResponse, TileData } from "@/components/warroom/executiveTypes";

export default function handler(req: NextApiRequest, res: NextApiResponse<SnapshotResponse>) {
  const tiles: TileData[] = [
    {
      key: "costTrendStress",
      title: "Cost Trend Stress Index",
      value: "11.2%",
      delta: "+2.2pp",
      subtitle: "vs 9% McKinsey baseline",
      trend: "down",
      framework: "McKinsey",
      chartData: [
        { period: "Q1", value: 8.5 },
        { period: "Q2", value: 9.1 },
        { period: "Q3", value: 10.3 },
        { period: "Q4", value: 11.2 },
      ],
      receipt: {
        receipt_id: "RX-2026-001-COST-TREND",
        owner: "CFO Office",
        freshness_minutes: 15,
        confidence: 0.94,
        dq_tests_passed: 47,
        dq_tests_total: 50,
        source_artifact_hash: "sha256:a7f8b2e9c4d1...",
        transform_hash: "sha256:3e5a9b1f7c2d...",
        verified: true,
        notes: "YoY net PMPM trend 220bps above McKinsey commercial baseline (9-10%). EBITDA at risk: $4.2M annualized.",
      },
    },
    {
      key: "planDesignAdoption",
      title: "Plan Design Innovation Adoption",
      value: "47%",
      delta: "+12pp QoQ",
      subtitle: "HDHP/HSA + COE enrollment",
      trend: "up",
      framework: "McKinsey",
      chartData: [
        { period: "Q1", value: 32 },
        { period: "Q2", value: 38 },
        { period: "Q3", value: 43 },
        { period: "Q4", value: 47 },
      ],
      receipt: {
        receipt_id: "RX-2026-002-PLAN-ADOPT",
        owner: "Benefits Strategy",
        freshness_minutes: 22,
        confidence: 0.91,
        dq_tests_passed: 44,
        dq_tests_total: 48,
        source_artifact_hash: "sha256:b8c3d4e5a1f2...",
        transform_hash: "sha256:4f6b0c2e8d3a...",
        verified: true,
        notes: "47% eligible population enrolled in innovative designs (HDHP/HSA steering, navigation, COE). Target: 60% by EOY.",
      },
    },
    {
      key: "pharmacyExposure",
      title: "Pharmacy Reimbursement Exposure",
      value: "34%",
      delta: "-8pp",
      subtitle: "Opaque vs cost-aligned",
      trend: "up",
      framework: "McKinsey",
      chartData: [
        { period: "Q1", value: 48 },
        { period: "Q2", value: 42 },
        { period: "Q3", value: 38 },
        { period: "Q4", value: 34 },
      ],
      receipt: {
        receipt_id: "RX-2026-003-PHARMACY-EXP",
        owner: "Pharmacy Operations",
        freshness_minutes: 18,
        confidence: 0.88,
        dq_tests_passed: 41,
        dq_tests_total: 46,
        source_artifact_hash: "sha256:c9d4e5f6b2a3...",
        transform_hash: "sha256:5g7c1d3f9e4b...",
        verified: true,
        notes: "34% Rx spend under opaque reimbursement terms. Shifting to cost-based models; target <25% by Q2 2026.",
      },
    },
    {
      key: "contractLeakage",
      title: "Contract Value Leakage Rate",
      value: "6.8%",
      delta: "-1.2pp",
      subtitle: "$8.3M recoverable EBITDA",
      trend: "up",
      framework: "McKinsey",
      chartData: [
        { period: "Q1", value: 8.9 },
        { period: "Q2", value: 8.1 },
        { period: "Q3", value: 7.4 },
        { period: "Q4", value: 6.8 },
      ],
      receipt: {
        receipt_id: "RX-2026-004-CONTRACT-LEAK",
        owner: "Procurement Ops",
        freshness_minutes: 12,
        confidence: 0.96,
        dq_tests_passed: 49,
        dq_tests_total: 50,
        source_artifact_hash: "sha256:d0e5f6a7c3b4...",
        transform_hash: "sha256:6h8d2e4g0f5c...",
        verified: true,
        notes: "Off-contract + pricing misses + missed rebates = 6.8% addressable spend. $8.3M recoverable via enforcement.",
      },
    },
    {
      key: "contractAmbiguity",
      title: "Contract Ambiguity Risk Score",
      value: "3.2/10",
      delta: "-0.8",
      subtitle: "Weighted by spend exposure",
      trend: "up",
      framework: "McKinsey",
      chartData: [
        { period: "Q1", value: 4.5 },
        { period: "Q2", value: 4.0 },
        { period: "Q3", value: 3.6 },
        { period: "Q4", value: 3.2 },
      ],
      receipt: {
        receipt_id: "RX-2026-005-CONTRACT-AMB",
        owner: "Legal + Procurement",
        freshness_minutes: 25,
        confidence: 0.89,
        dq_tests_passed: 42,
        dq_tests_total: 47,
        source_artifact_hash: "sha256:e1f6a7b8d4c5...",
        transform_hash: "sha256:7i9e3f5h1g6d...",
        verified: true,
        notes: "Clause-quality score improving (definitions, audit rights, pricing terms). High-spend contracts remediated Q3-Q4.",
      },
    },
    {
      key: "contractCompliance",
      title: "Contract Compliance Rate",
      value: "92.4%",
      delta: "+3.1pp",
      subtitle: "Compliant adjudications",
      trend: "up",
      framework: "McKinsey",
      chartData: [
        { period: "Q1", value: 87.2 },
        { period: "Q2", value: 89.1 },
        { period: "Q3", value: 90.8 },
        { period: "Q4", value: 92.4 },
      ],
      receipt: {
        receipt_id: "RX-2026-006-CONTRACT-COMP",
        owner: "Compliance + Audit",
        freshness_minutes: 20,
        confidence: 0.93,
        dq_tests_passed: 46,
        dq_tests_total: 49,
        source_artifact_hash: "sha256:f2g7b8c9e5d6...",
        transform_hash: "sha256:8j0f4g6i2h7e...",
        verified: true,
        notes: "92.4% compliant invoices/claims. Non-compliance spend reduced by $2.1M QoQ via enforcement automation.",
      },
    },
    {
      key: "benefitsNPS",
      title: "Benefits NPS",
      value: "+38",
      delta: "+7 pts",
      subtitle: "Employee benefits experience",
      trend: "up",
      framework: "Bain",
      chartData: [
        { period: "Q1", value: 28 },
        { period: "Q2", value: 31 },
        { period: "Q3", value: 35 },
        { period: "Q4", value: 38 },
      ],
      receipt: {
        receipt_id: "RX-2026-007-BENEFITS-NPS",
        owner: "Employee Experience",
        freshness_minutes: 30,
        confidence: 0.87,
        dq_tests_passed: 40,
        dq_tests_total: 45,
        source_artifact_hash: "sha256:g3h8c9d0f6e7...",
        transform_hash: "sha256:9k1g5h7j3i8f...",
        verified: true,
        notes: "Bain NPS for enrollment, claims, navigation, pharmacy experience. +7 pts QoQ; correlation with plan adoption.",
      },
    },
    {
      key: "employeeNPS",
      title: "Employee NPS (eNPS)",
      value: "+42",
      delta: "+5 pts",
      subtitle: "Benefits team + vendors",
      trend: "up",
      framework: "Bain",
      chartData: [
        { period: "Q1", value: 34 },
        { period: "Q2", value: 37 },
        { period: "Q3", value: 40 },
        { period: "Q4", value: 42 },
      ],
      receipt: {
        receipt_id: "RX-2026-008-EMPLOYEE-NPS",
        owner: "People Ops",
        freshness_minutes: 28,
        confidence: 0.90,
        dq_tests_passed: 43,
        dq_tests_total: 47,
        source_artifact_hash: "sha256:h4i9d0e1g7f8...",
        transform_hash: "sha256:0l2h6i8k4j9g...",
        verified: true,
        notes: "eNPS for internal benefits ops + vendor service teams. Leading indicator of execution quality and retention.",
      },
    },
  ];

  const tickerItems = [
    "Cost Trend Stress: 11.2% YoY PMPM — 220bps above McKinsey baseline → $4.2M EBITDA at risk",
    "Plan Design Adoption: 47% enrollment in HDHP/HSA + COE — +12pp QoQ → McKinsey innovation hedge",
    "Pharmacy Exposure: 34% Rx spend under opaque terms — shifting to cost-based → target <25% Q2'26",
    "Contract Leakage: 6.8% addressable spend → $8.3M recoverable via pricing/rebate enforcement",
    "Contract Ambiguity: 3.2/10 risk score — high-spend contracts remediated Q3-Q4 → dispute mitigation",
    "Contract Compliance: 92.4% adjudication rate — +3.1pp QoQ → $2.1M non-compliance spend reduced",
    "Benefits NPS: +38 (Bain framework) — +7 pts QoQ → correlation with plan adoption and loyalty",
    "Employee NPS: +42 (Bain eNPS) — internal ops + vendor partners → execution quality leading indicator",
    "McKinsey Framework: Cost management via trend stress, contract value, pharmacy exposure, compliance",
    "Bain NPS System: Experience + loyalty metrics as leading indicators of adoption and retention success",
    "Evidence Receipts: 100% KPI coverage — cryptographic proof, DQ validation, source lineage, confidence >87%",
    "CFO Cadence: Weekly exec rhythm + board updates — audit-grade defensibility → Detect, Prove, Act, Realize",
  ];

  res.status(200).json({ tiles, tickerItems });
}