import type { NextApiRequest, NextApiResponse } from "next";
import type { SnapshotResponse, TileData } from "@/components/warroom/executiveTypes";

export default function handler(req: NextApiRequest, res: NextApiResponse<SnapshotResponse>) {
  const tiles: TileData[] = [
    {
      key: "costTrendStress",
      title: "Cost Trend Stress Index",
      value: "11.2%",
      delta: "+2.2%",
      trend: "down",
      subtitle: "YoY PMPM vs 9-10% McKinsey benchmark",
      chartData: [
        { period: "Q1", value: 8.5 },
        { period: "Q2", value: 9.1 },
        { period: "Q3", value: 10.3 },
        { period: "Q4", value: 11.2 },
      ],
      receipt: {
        receipt_id: "rcpt_cost_trend_2026_q4",
        source_artifact_hash: "sha256:8f4e9a3b2c1d0e5f6a7b8c9d0e1f2a3b",
        transform_hash: "sha256:1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d",
        freshness_minutes: 45,
        dq_tests_passed: 12,
        dq_tests_total: 12,
        owner: "CFO Office",
        confidence: 0.94,
        verified: true,
        notes: "PMPM trend calculated from claims + enrollment census; McKinsey 2024-2026 benchmark applied",
      },
    },
    {
      key: "planDesignAdoption",
      title: "Plan Design Innovation Adoption",
      value: "68%",
      delta: "+12%",
      trend: "up",
      subtitle: "HDHP/HSA, navigation, CoE enrollment",
      chartData: [
        { period: "Q1", value: 56 },
        { period: "Q2", value: 61 },
        { period: "Q3", value: 65 },
        { period: "Q4", value: 68 },
      ],
      receipt: {
        receipt_id: "rcpt_plan_adoption_2026_q4",
        source_artifact_hash: "sha256:2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e",
        transform_hash: "sha256:7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b",
        freshness_minutes: 30,
        dq_tests_passed: 10,
        dq_tests_total: 10,
        owner: "Benefits Strategy",
        confidence: 0.91,
        verified: true,
        notes: "Enrollment data from benefits admin platform; innovative designs per McKinsey framework",
      },
    },
    {
      key: "pharmacyExposure",
      title: "Pharmacy Reimbursement Exposure",
      value: "34%",
      delta: "-8%",
      trend: "up",
      subtitle: "% Rx spend under opaque terms",
      chartData: [
        { period: "Q1", value: 42 },
        { period: "Q2", value: 39 },
        { period: "Q3", value: 37 },
        { period: "Q4", value: 34 },
      ],
      receipt: {
        receipt_id: "rcpt_pharmacy_exposure_2026_q4",
        source_artifact_hash: "sha256:3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f",
        transform_hash: "sha256:8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c",
        freshness_minutes: 60,
        dq_tests_passed: 11,
        dq_tests_total: 12,
        owner: "Pharmacy Benefits",
        confidence: 0.88,
        verified: true,
        notes: "PBM contract analysis; tracking migration to cost-based reimbursement models",
      },
    },
    {
      key: "contractLeakage",
      title: "Contract Value Leakage Rate",
      value: "7.3%",
      delta: "-1.2%",
      trend: "up",
      subtitle: "Off-contract + pricing misses + rebates",
      chartData: [
        { period: "Q1", value: 8.5 },
        { period: "Q2", value: 8.1 },
        { period: "Q3", value: 7.8 },
        { period: "Q4", value: 7.3 },
      ],
      receipt: {
        receipt_id: "rcpt_contract_leakage_2026_q4",
        source_artifact_hash: "sha256:4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a",
        transform_hash: "sha256:9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d",
        freshness_minutes: 35,
        dq_tests_passed: 14,
        dq_tests_total: 14,
        owner: "Procurement",
        confidence: 0.96,
        verified: true,
        notes: "Contract enforcement audit vs addressable spend; McKinsey leakage framework applied",
      },
    },
    {
      key: "contractAmbiguity",
      title: "Contract Ambiguity Risk Score",
      value: "2.8",
      delta: "-0.4",
      trend: "up",
      subtitle: "Clause quality weighted by spend (1-5)",
      chartData: [
        { period: "Q1", value: 3.2 },
        { period: "Q2", value: 3.1 },
        { period: "Q3", value: 2.9 },
        { period: "Q4", value: 2.8 },
      ],
      receipt: {
        receipt_id: "rcpt_ambiguity_score_2026_q4",
        source_artifact_hash: "sha256:5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b",
        transform_hash: "sha256:0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e",
        freshness_minutes: 90,
        dq_tests_passed: 9,
        dq_tests_total: 10,
        owner: "Legal & Compliance",
        confidence: 0.85,
        verified: true,
        notes: "Clause scoring: definitions, audit rights, pricing transparency, pass-through, termination, data rights",
      },
    },
    {
      key: "contractCompliance",
      title: "Contract Compliance Rate",
      value: "94.2%",
      delta: "+2.1%",
      trend: "up",
      subtitle: "Compliant invoices/adjudications",
      chartData: [
        { period: "Q1", value: 92.1 },
        { period: "Q2", value: 92.8 },
        { period: "Q3", value: 93.5 },
        { period: "Q4", value: 94.2 },
      ],
      receipt: {
        receipt_id: "rcpt_compliance_2026_q4",
        source_artifact_hash: "sha256:6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c",
        transform_hash: "sha256:1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f",
        freshness_minutes: 25,
        dq_tests_passed: 13,
        dq_tests_total: 13,
        owner: "Finance Operations",
        confidence: 0.97,
        verified: true,
        notes: "Invoice/claims validation vs contract terms; enforcement scorecard per McKinsey framework",
      },
    },
    {
      key: "benefitsNPS",
      title: "Benefits NPS",
      value: "42",
      delta: "+8",
      trend: "up",
      subtitle: "Employee benefits experience score",
      chartData: [
        { period: "Q1", value: 34 },
        { period: "Q2", value: 37 },
        { period: "Q3", value: 40 },
        { period: "Q4", value: 42 },
      ],
      receipt: {
        receipt_id: "rcpt_benefits_nps_2026_q4",
        source_artifact_hash: "sha256:7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d",
        transform_hash: "sha256:2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a",
        freshness_minutes: 120,
        dq_tests_passed: 8,
        dq_tests_total: 9,
        owner: "HR & Benefits",
        confidence: 0.82,
        verified: true,
        notes: "Quarterly survey: enrollment, claims, navigation, pharmacy experience; Bain NPS methodology",
      },
    },
    {
      key: "employeeNPS",
      title: "Employee NPS (eNPS)",
      value: "38",
      delta: "+5",
      trend: "up",
      subtitle: "Benefits team & vendor partners",
      chartData: [
        { period: "Q1", value: 33 },
        { period: "Q2", value: 35 },
        { period: "Q3", value: 37 },
        { period: "Q4", value: 38 },
      ],
      receipt: {
        receipt_id: "rcpt_enps_2026_q4",
        source_artifact_hash: "sha256:8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e",
        transform_hash: "sha256:3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b",
        freshness_minutes: 150,
        dq_tests_passed: 7,
        dq_tests_total: 8,
        owner: "HR Operations",
        confidence: 0.79,
        verified: false,
        notes: "Internal ops + vendor service teams; Bain eNPS framework for operational health",
      },
    },
  ];

  const tickerItems = [
    "Contract compliance improved 2.1% QoQ — enforcement initiatives taking hold",
    "Plan design adoption reached 68% — HDHP/HSA steering + navigation programs driving uptake",
    "Pharmacy exposure reduced to 34% — migration to cost-based reimbursement on track",
    "Cost trend stress at 11.2% — exceeding McKinsey 9-10% benchmark, intervention required",
    "Benefits NPS climbed to 42 — enrollment + claims experience improvements paying off",
    "Contract leakage rate down to 7.3% — procurement governance tightening",
  ];

  res.status(200).json({ tiles, tickerItems });
}